version: '3.8'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coze-plus-docs
    restart: unless-stopped
    ports:
      - "${DOCS_PORT:-8080}:80"
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.cozeplus.service=docs"
      - "com.cozeplus.description=Coze Plus Documentation"
